name: AWS Lambda Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy package.json to dist
        run: cp package.json dist/ && cp package-lock.json dist/ || true

      - name: Install Production Dependencies
        run: cd dist && npm install --production

      - name: Zip
        run: (cd dist && zip -r ../function.zip .)

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: clipquiz-api
          zip_file: function.zip
          handler: lambda.handler

      - name: Migrate Database
        run: npm run migration:migrate
