name: test-workflow

on: [push]

env:
  NODE_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?schema=public

jobs:
  test:
    environment: test
    env:
      CLIENT_URL: ${{ vars.CLIENT_URL }}
      GOOGLE_OAUTH2_CLIENT_ID: ${{ vars.GOOGLE_OAUTH2_CLIENT_ID }}
      GOOGLE_OAUTH2_SECRET: ${{ vars.GOOGLE_OAUTH2_SECRET }}
      SESSION_SALT: ${{ vars.SESSION_SALT }}
      SESSION_SECRET: ${{ vars.SESSION_SECRET }}
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Check Build
        run: npm run build

      - name: Check Types and Lint
        run: npm run check

      - name: Migrate Database
        run: npm run db:migrate

      - name: Run Tests
        run: npm test
