name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: test
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: postgres
  DATABASE_SSL: false

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ env.DATABASE_USERNAME}}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{ env.DATABASE_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Check Build
        run: npm run build

      - name: Check Project
        run: npm run check

      - name: Migrate Database
        run: npm run migration:migrate

      - name: Test
        run: npm test
